# Generated by Django 6.0.1 on 2026-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "SocialLink",
            },
        ),
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "About"},
        ),
    ]
